routes/admin.php
<?php

    Route::GET('/home', 'AdminController@index')->name('admin.home');
    // Login and Logout
    Route::GET('/', 'LoginController@showLoginForm')->name('admin.login');
    Route::POST('/', 'LoginController@login');
    Route::POST('/logout', 'LoginController@logout')->name('admin.logout');

    // Password Resets
    Route::POST('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    Route::GET('/password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::POST('/password/reset', 'ResetPasswordController@reset');
    Route::GET('/password/reset/{token}', 'ResetPasswordController@showResetForm')->name('admin.password.reset');
    Route::GET('/password/change', 'AdminController@showChangePasswordForm')->name('admin.password.change');
    Route::POST('/password/change', 'AdminController@changePassword');

    // Register Admins
    Route::get('/register', 'RegisterController@showRegistrationForm')->name('admin.register');
    Route::post('/register', 'RegisterController@register');
    Route::get('/{admin}/edit', 'RegisterController@edit')->name('admin.edit');
    Route::delete('/{admin}', 'RegisterController@destroy')->name('admin.delete');
    Route::patch('/{admin}', 'RegisterController@update')->name('admin.update');

    // Admin Lists
    Route::get('/show', 'AdminController@show')->name('admin.show');
    Route::get('/me', 'AdminController@me')->name('admin.me');

    // Admin Roles
    Route::post('/{admin}/role/{role}', 'AdminRoleController@attach')->name('admin.attach.roles');
    Route::delete('/{admin}/role/{role}', 'AdminRoleController@detach');

    // Roles
    Route::get('/roles', 'RoleController@index')->name('admin.roles');
    Route::get('/role/create', 'RoleController@create')->name('admin.role.create');
    Route::post('/role/store', 'RoleController@store')->name('admin.role.store');
    Route::delete('/role/{role}', 'RoleController@destroy')->name('admin.role.delete');
    Route::get('/role/{role}/edit', 'RoleController@edit')->name('admin.role.edit');
    Route::patch('/role/{role}', 'RoleController@update')->name('admin.role.update');

    // active status
    Route::post('activation/{admin}', 'ActivationController@activate')->name('admin.activation');
    Route::delete('activation/{admin}', 'ActivationController@deactivate');
    Route::resource('permission', 'PermissionController');

    Route::fallback(function () {
        return abort(404);
    });

routes/web.php
    Route::get('/coach/lessons', 'CustomerDashboard\DashboardController@CoachLesson')->name('coach.lessons');
    Route::get('/lessons/manage', 'CustomerDashboard\DashboardController@CoachLessonManage');
    Route::get('/lessons/manage/show/{id}', 'CustomerDashboard\DashboardController@CoachLessonManageShow');
    Route::delete('/lessons/delete/{id}', 'CustomerDashboard\DashboardController@CoachLessonDelete')->name('courseCoaoch.destroy');
    ////// STORE COURSE CART
    Route::post('/lessons/store/cart', 'CustomerDashboard\DashboardController@LessonStoreCart');
    Route::post('/lessons/save', 'CustomerDashboard\DashboardController@CoachLessonSave');

    Route::get('/coach/calendar', 'CustomerDashboard\DashboardController@CoachCalendar')->name('coach.calendar');
    Route::post('/coach/calendar', 'CustomerDashboard\DashboardController@CoachCalendarPost')->name('coach.calendar.post');

    /******** BOOKING COACH **************/
    Route::post('/save/booking', 'CustomerDashboard\DashboardController@saveBookingCoach')->name('saveBooking');

    /*************** BOOKING PAYMENT **************/
    Route::post('/booking/payment', 'CustomerDashboard\DashboardController@GoPaymentHandler')->name('booking.payment');

    Route::get('/page/payment', 'CustomerDashboard\DashboardController@PagePay');

    Route::get('/go/payment', 'CustomerDashboard\DashboardController@PagePay');

    // Route::post('/payment/notify', 'CustomerDashboard\DashboardController@PayNotify');

    Route::get('viewinvoice/{id}', 'CustomerDashboard\DashboardController@getInvoice');

    ////// REVIEWBOOKING ////////////////
    Route::post('/save/review', 'CustomerDashboard\DashboardController@saveReview');

    Route::get('/tickets', 'CustomerDashboard\DashboardController@tickets');
    Route::get('/tickets/pdf/{id}', 'CustomerDashboard\DashboardController@ticketPdf');
    Route::get('/tickets/view/{id}', 'CustomerDashboard\DashboardController@ticketView');
    Route::get('/tickets/{id}', 'CustomerDashboard\DashboardController@ticket');
    Route::get('/orders/shop', 'CustomerDashboard\DashboardController@shopOrders');
    Route::get('/orders/shop/{orderId}', 'CustomerDashboard\DashboardController@shopOrder');
    Route::get('/notifications', 'CustomerDashboard\DashboardController@notifications');
    Route::get('/coupons', 'CustomerDashboard\DashboardController@coupons');
    Route::get('/packs', 'CustomerDashboard\DashboardController@packs');
    Route::get('/coaches', 'CustomerDashboard\DashboardController@coaches');

    // Liste à garder pour plus tard
    Route::get('/wishlist/toggle/{id}', 'CustomerDashboard\DashboardController@wishlistToggle')->name('wishlist.toggle');
    Route::get('/wishlist', 'CustomerDashboard\DashboardController@showWishlist')->name('wishlist.index');
    // Customer reviews
    Route::get('/reviews', 'CustomerDashboard\DashboardController@showReviews')->name('reviews.index');
    Route::get('/reviews/create/{orderId}/{productId}', 'CustomerDashboard\DashboardController@createReviews')->name('customer.reviews.create');
    Route::get('/reviews/course/{courseId}', 'CustomerDashboard\DashboardController@createReviewsCourse')->name('customer.reviews.create_course');
    Route::post('/reviews/store', 'CustomerDashboard\DashboardController@storeReviews')->name('customer.reviews.store');
    Route::post('/reviews/store_course', 'CustomerDashboard\DashboardController@storeReviewsCourse')->name('customer.reviews.store_course');

});

// ** ** Disciplines
Route::get('/customer/disciplines', 'CustomerFrontOfficeController@disciplines');

/////////////// END ROUTE HOME PAGE ///////////////

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes([
    'verify' => true,
    'register'  => false
]);

// Route::get('/home', 'HomeController@index')->middleware('verified');
Route::get('/analytique', 'AnalytiqueController@index');

Route::get('/partner/download/all', 'PartnerController@printAll');
Route::get('/customers/download/all', 'CustomerController@printAll');
Route::get('/product/download/all', 'ProductController@printAll');
Route::get('/event/download/all', 'EventController@printAll');
Route::get('/order/download/all', 'OrderController@printAll');
Route::get('/coupon/download/all', 'CouponController@printAll');
Route::get('/booking/download/all', 'BookingCoachController@printAll');
Route::get('/contact/download/all', 'ContactRequestController@printAll');
Route::get('/coach/download/all', 'CoachController@printAll');


Route::resource('coaches', 'CoachController');
Route::post('find/coach', 'CoachController@searchCoach')->name('searchCoach');
Route::post('find/product', 'ProductController@searchProduct')->name('searchProduct');
Route::post('find/partner', 'PartnerController@searchPartner')->name('searchPartner');
Route::post('find/event', 'EventController@searchEvent')->name('searchEvent');
Route::post('find/order', 'OrderController@searchOrder')->name('searchOrder');
Route::post('find/bookingCoach', 'BookingCoachController@searchBookingCoach')->name('searchBookingCoach');
Route::resource('product-reservation', 'ProductReservationController');

Route::resource('customers', 'CustomerController');
Route::post('find/customer', 'CustomerController@searchCustomer')->name('searchCustomer');

Route::resource('languages', 'LanguageController');

Route::resource('availabilities', 'AvailabilityController');

Route::resource('disciplines', 'DisciplineController');

Route::resource('coachDisciplines', 'CoachDisciplineController');

Route::resource('packs', 'PackController');

Route::resource('packSubscriptions', 'PackSubscriptionController');

Route::resource('portfolios', 'PortfolioController');

Route::resource('events', 'EventController');

Route::resource('orders', 'OrderController');
Route::post('/order/espece/{id}', 'OrderController@espece')->name('orders.espece');
Route::post('/order/isPaid/{id}', 'OrderController@changeStatus')->name('orders.isPaid');
Route::post('/order/changeStatus/{id}', 'OrderController@changeStatus')->name('orders.changeStatus');
Route::post('/customer/changeStatus/{id}', 'CustomerController@changeStatus')->name('customer.changeStatus');
Route::post('/coach/changeStatus/{id}', 'CoachController@changeStatus')->name('coach.changeStatus');

Route::resource('bodyMassIndices', 'BodyMassIndexController');

Route::resource('recapBMIs', 'RecapBMIController');

Route::resource('recapBMIs', 'RecapBMIController');

Route::resource('addresses', 'AddressController');

Route::resource('coupons', 'CouponController');

Route::resource('invoices', 'InvoiceController');

Route::resource('courses', 'CourseController');
Route::post('/course/changeStatus/{id}', 'CourseController@changeStatus')->name('course.changeStatus');
Route::get('/sendMail', 'HomeController@sendMail')->name('sendMail');
Route::post('/sendMail', 'HomeController@sendMailPost')->name('sendMailPost');
Route::get('viewinvoice/{id}', 'OrderController@invoiceFacture');

Route::resource('services', 'ServiceController');

Route::resource('products', 'ProductController');
Route::post('/product/stock/{id}', 'ProductController@stock')->name('stock_update');

Route::resource('experiences', 'ExperienceController');

Route::resource('qualifications', 'QualificationController');

Route::resource('qualificationTypes', 'QualificationTypeController');

Route::resource('invoicePayments', 'InvoicePaymentController');

Route::resource('invoicePayments', 'InvoicePaymentController');

Route::resource('notes', 'NoteController');

Route::resource('advice', 'AdviceController');

Route::resource('objectives', 'ObjectiveController');

Route::resource('seances', 'SeanceController');


Route::resource('howDidYouKnows', 'HowDidYouKnowController');

Route::resource('partners', 'PartnerController');


Route::resource('connexions', 'ConnexionController');


Route::resource('categories', 'CategoryController');

Route::resource('posts', 'PostController');

Route::resource('orderItems', 'OrderItemController');


Route::resource('courseDetails', 'courseDetailsController');

Route::resource('courseLieus', 'courseLieuController');

Route::resource('lieuCourses', 'LieuCourseController');

Route::resource('courseObjectives', 'CourseObjectiveController');

Route::resource('bookingCoaches', 'BookingCoachController');


Route::resource('productCategories', 'ProductCategoryController');

Route::resource('adverts', 'AdvertController');
Route::resource('users', 'UserController');


Route::get('/mail/test', function () {

    $user = [
        'name' => 'Mahedi Hasan',
        'info' => 'Laravel Developer'
    ];

    \Mail::to('jacques.bagui@gmail.com')->send(new \App\Mail\NewMail($user));

    dd("success");
});

Route::get('videotheque', 'CustomerFrontOfficeController@videothequeIndex');

Route::resource('distinctions', 'distinctionController');

Route::resource('videotheques', 'VideothequeController');





Route::resource('clientTestimonies', 'ClientTestimonyController');

Route::resource('programs', 'ProgramController');


Route::resource('slides', 'SlideController');
Route::resource('diplomes', 'DiplomeController');

Route::resource('customerDevices', 'CustomerDeviceController');

Route::resource('customerNotifications', 'CustomerNotificationController');
Route::post('resend-email', 'CustomerNotificationController@resendEmailSubcription')->name('resendEmailSubcription');





Route::resource('reviews', 'ReviewController');

Route::get('/fetchVisitorsAndPageViews', 'AnalytiqueController@fetchVisitorsAndPageViews');
Route::get('/fetchTotalVisitorsAndPageViews', 'AnalytiqueController@fetchTotalVisitorsAndPageViews');
Route::get('/fetchMostVisitedPages', 'AnalytiqueController@fetchMostVisitedPages');
Route::get('/fetchTimeOnPages', 'AnalytiqueController@fetchTimeOnPages');
Route::get('/fetchTopReferrers', 'AnalytiqueController@fetchTopReferrers');
Route::get('/fetchUserTypes', 'AnalytiqueController@fetchUserTypes');

app/Models/CoachDiscipline.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class CoachDiscipline
 * @package App\Models
 * @version July 29, 2020, 6:11 pm UTC
 *
 * @property integer $coach_id
 * @property integer $discipline_id
 */
class CoachDiscipline extends Model
{
    use SoftDeletes;

    public $table = 'coach_disciplines';
    

    protected $dates = ['deleted_at'];

    public $appends = [
        'coachs',
        'discipline'
    ];

    public $fillable = [
        'coach_id',
        'discipline_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'coach_id' => 'integer',
        'discipline_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    public function getDisciplineAttribute(){
        return Discipline::where("id", $this->discipline_id)->first();
    }
    
    public function getCoachsAttribute(){
        return Coach::where("id", $this->coach_id)->get() ?? [];
    }

}

app/Http/Controllers/CoachDisciplineController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateCoachDisciplineRequest;
use App\Http\Requests\UpdateCoachDisciplineRequest;
use App\Repositories\CoachDisciplineRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class CoachDisciplineController extends AppBaseController
{
    /** @var  CoachDisciplineRepository */
    private $coachDisciplineRepository;

    public function __construct(CoachDisciplineRepository $coachDisciplineRepo)
    {
        $this->coachDisciplineRepository = $coachDisciplineRepo;
    }

    /**
     * Display a listing of the CoachDiscipline.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $coachDisciplines = $this->coachDisciplineRepository->all();

        return view('coach_disciplines.index')
            ->with('coachDisciplines', $coachDisciplines);
    }

    /**
     * Show the form for creating a new CoachDiscipline.
     *
     * @return Response
     */
    public function create()
    {
        return view('coach_disciplines.create');
    }

    /**
     * Store a newly created CoachDiscipline in storage.
     *
     * @param CreateCoachDisciplineRequest $request
     *
     * @return Response
     */
    public function store(CreateCoachDisciplineRequest $request)
    {
        $input = $request->all();

        $coachDiscipline = $this->coachDisciplineRepository->create($input);

        Flash::success('Coach Discipline saved successfully.');

        return redirect(route('coachDisciplines.index'));
    }

    /**
     * Display the specified CoachDiscipline.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $coachDiscipline = $this->coachDisciplineRepository->find($id);

        if (empty($coachDiscipline)) {
            Flash::error('Coach Discipline not found');

            return redirect(route('coachDisciplines.index'));
        }

        return view('coach_disciplines.show')->with('coachDiscipline', $coachDiscipline);
    }

    /**
     * Show the form for editing the specified CoachDiscipline.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $coachDiscipline = $this->coachDisciplineRepository->find($id);

        if (empty($coachDiscipline)) {
            Flash::error('Coach Discipline not found');

            return redirect(route('coachDisciplines.index'));
        }

        return view('coach_disciplines.edit')->with('coachDiscipline', $coachDiscipline);
    }

    /**
     * Update the specified CoachDiscipline in storage.
     *
     * @param int $id
     * @param UpdateCoachDisciplineRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCoachDisciplineRequest $request)
    {
        $coachDiscipline = $this->coachDisciplineRepository->find($id);

        if (empty($coachDiscipline)) {
            Flash::error('Coach Discipline not found');

            return redirect(route('coachDisciplines.index'));
        }

        $coachDiscipline = $this->coachDisciplineRepository->update($request->all(), $id);

        Flash::success('Coach Discipline updated successfully.');

        return redirect(route('coachDisciplines.index'));
    }

    /**
     * Remove the specified CoachDiscipline from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $coachDiscipline = $this->coachDisciplineRepository->find($id);

        if (empty($coachDiscipline)) {
            Flash::error('Coach Discipline not found');

            return redirect(route('coachDisciplines.index'));
        }

        $this->coachDisciplineRepository->delete($id);

        Flash::success('Coach Discipline deleted successfully.');

        return redirect(route('coachDisciplines.index'));
    }
}

resources/views/coach_disciplines/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('coachDisciplines.index') !!}">Coach Discipline</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Coach Discipline</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'coachDisciplines.store']) !!}

                                   @include('coach_disciplines.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/coach_disciplines/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('coachDisciplines.index') !!}">Coach Discipline</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Coach Discipline</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($coachDiscipline, ['route' => ['coachDisciplines.update', $coachDiscipline->id], 'method' => 'patch']) !!}

                              @include('coach_disciplines.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/coach_disciplines/fields.blade.php
<!-- Coach Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('coach_id', 'Coach Id:') !!}
    {!! Form::select('coach_id', $coachItems, null, ['class' => 'form-control']) !!}
</div>

<!-- Discipline Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('discipline_id', 'Discipline Id:') !!}
    {!! Form::select('discipline_id', $disciplineItems, null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('coachDisciplines.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/coach_disciplines/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Coach Disciplines</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             CoachDisciplines
                             <a class="pull-right" href="{{ route('coachDisciplines.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('coach_disciplines.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/coach_disciplines/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('coachDisciplines.index') }}">Coach Discipline</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('coachDisciplines.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('coach_disciplines.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/coach_disciplines/show_fields.blade.php
<!-- Coach Id Field -->
<div class="form-group">
    {!! Form::label('coach_id', 'Coach Id:') !!}
    <p>{{ $coachDiscipline->coach_id }}</p>
</div>

<!-- Discipline Id Field -->
<div class="form-group">
    {!! Form::label('discipline_id', 'Discipline Id:') !!}
    <p>{{ $coachDiscipline->discipline_id }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $coachDiscipline->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $coachDiscipline->updated_at }}</p>
</div>

resources/views/coach_disciplines/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="coachDisciplines-table">
        <thead>
            <tr>
                <th>Coach Id</th>
        <th>Discipline Id</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($coachDisciplines as $coachDiscipline)
            <tr>
                <td>{{ $coachDiscipline->coach_id }}</td>
            <td>{{ $coachDiscipline->discipline_id }}</td>
                <td>
                    {!! Form::open(['route' => ['coachDisciplines.destroy', $coachDiscipline->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('coachDisciplines.show', [$coachDiscipline->id]) }}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{{ route('coachDisciplines.edit', [$coachDiscipline->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>