routes/admin.php
<?php

    Route::GET('/home', 'AdminController@index')->name('admin.home');
    // Login and Logout
    Route::GET('/', 'LoginController@showLoginForm')->name('admin.login');
    Route::POST('/', 'LoginController@login');
    Route::POST('/logout', 'LoginController@logout')->name('admin.logout');

    // Password Resets
    Route::POST('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    Route::GET('/password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::POST('/password/reset', 'ResetPasswordController@reset');
    Route::GET('/password/reset/{token}', 'ResetPasswordController@showResetForm')->name('admin.password.reset');
    Route::GET('/password/change', 'AdminController@showChangePasswordForm')->name('admin.password.change');
    Route::POST('/password/change', 'AdminController@changePassword');

    // Register Admins
    Route::get('/register', 'RegisterController@showRegistrationForm')->name('admin.register');
    Route::post('/register', 'RegisterController@register');
    Route::get('/{admin}/edit', 'RegisterController@edit')->name('admin.edit');
    Route::delete('/{admin}', 'RegisterController@destroy')->name('admin.delete');
    Route::patch('/{admin}', 'RegisterController@update')->name('admin.update');

    // Admin Lists
    Route::get('/show', 'AdminController@show')->name('admin.show');
    Route::get('/me', 'AdminController@me')->name('admin.me');

    // Admin Roles
    Route::post('/{admin}/role/{role}', 'AdminRoleController@attach')->name('admin.attach.roles');
    Route::delete('/{admin}/role/{role}', 'AdminRoleController@detach');

    // Roles
    Route::get('/roles', 'RoleController@index')->name('admin.roles');
    Route::get('/role/create', 'RoleController@create')->name('admin.role.create');
    Route::post('/role/store', 'RoleController@store')->name('admin.role.store');
    Route::delete('/role/{role}', 'RoleController@destroy')->name('admin.role.delete');
    Route::get('/role/{role}/edit', 'RoleController@edit')->name('admin.role.edit');
    Route::patch('/role/{role}', 'RoleController@update')->name('admin.role.update');

    // active status
    Route::post('activation/{admin}', 'ActivationController@activate')->name('admin.activation');
    Route::delete('activation/{admin}', 'ActivationController@deactivate');
    Route::resource('permission', 'PermissionController');

    Route::fallback(function () {
        return abort(404);
    });

routes/web.php
    Route::get('/coach/lessons', 'CustomerDashboard\DashboardController@CoachLesson')->name('coach.lessons');
    Route::get('/lessons/manage', 'CustomerDashboard\DashboardController@CoachLessonManage');
    Route::get('/lessons/manage/show/{id}', 'CustomerDashboard\DashboardController@CoachLessonManageShow');
    Route::delete('/lessons/delete/{id}', 'CustomerDashboard\DashboardController@CoachLessonDelete')->name('courseCoaoch.destroy');
    ////// STORE COURSE CART
    Route::post('/lessons/store/cart', 'CustomerDashboard\DashboardController@LessonStoreCart');
    Route::post('/lessons/save', 'CustomerDashboard\DashboardController@CoachLessonSave');

    Route::get('/coach/calendar', 'CustomerDashboard\DashboardController@CoachCalendar')->name('coach.calendar');
    Route::post('/coach/calendar', 'CustomerDashboard\DashboardController@CoachCalendarPost')->name('coach.calendar.post');

    /******** BOOKING COACH **************/
    Route::post('/save/booking', 'CustomerDashboard\DashboardController@saveBookingCoach')->name('saveBooking');

    /*************** BOOKING PAYMENT **************/
    Route::post('/booking/payment', 'CustomerDashboard\DashboardController@GoPaymentHandler')->name('booking.payment');

    Route::get('/page/payment', 'CustomerDashboard\DashboardController@PagePay');

    Route::get('/go/payment', 'CustomerDashboard\DashboardController@PagePay');

    // Route::post('/payment/notify', 'CustomerDashboard\DashboardController@PayNotify');

    Route::get('viewinvoice/{id}', 'CustomerDashboard\DashboardController@getInvoice');

    ////// REVIEWBOOKING ////////////////
    Route::post('/save/review', 'CustomerDashboard\DashboardController@saveReview');

    Route::get('/tickets', 'CustomerDashboard\DashboardController@tickets');
    Route::get('/tickets/pdf/{id}', 'CustomerDashboard\DashboardController@ticketPdf');
    Route::get('/tickets/view/{id}', 'CustomerDashboard\DashboardController@ticketView');
    Route::get('/tickets/{id}', 'CustomerDashboard\DashboardController@ticket');
    Route::get('/orders/shop', 'CustomerDashboard\DashboardController@shopOrders');
    Route::get('/orders/shop/{orderId}', 'CustomerDashboard\DashboardController@shopOrder');
    Route::get('/notifications', 'CustomerDashboard\DashboardController@notifications');
    Route::get('/coupons', 'CustomerDashboard\DashboardController@coupons');
    Route::get('/packs', 'CustomerDashboard\DashboardController@packs');
    Route::get('/coaches', 'CustomerDashboard\DashboardController@coaches');

    // Liste à garder pour plus tard
    Route::get('/wishlist/toggle/{id}', 'CustomerDashboard\DashboardController@wishlistToggle')->name('wishlist.toggle');
    Route::get('/wishlist', 'CustomerDashboard\DashboardController@showWishlist')->name('wishlist.index');
    // Customer reviews
    Route::get('/reviews', 'CustomerDashboard\DashboardController@showReviews')->name('reviews.index');
    Route::get('/reviews/create/{orderId}/{productId}', 'CustomerDashboard\DashboardController@createReviews')->name('customer.reviews.create');
    Route::get('/reviews/course/{courseId}', 'CustomerDashboard\DashboardController@createReviewsCourse')->name('customer.reviews.create_course');
    Route::post('/reviews/store', 'CustomerDashboard\DashboardController@storeReviews')->name('customer.reviews.store');
    Route::post('/reviews/store_course', 'CustomerDashboard\DashboardController@storeReviewsCourse')->name('customer.reviews.store_course');

});

// ** ** Disciplines
Route::get('/customer/disciplines', 'CustomerFrontOfficeController@disciplines');

/////////////// END ROUTE HOME PAGE ///////////////

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes([
    'verify' => true,
    'register'  => false
]);

// Route::get('/home', 'HomeController@index')->middleware('verified');
Route::get('/analytique', 'AnalytiqueController@index');

Route::get('/partner/download/all', 'PartnerController@printAll');
Route::get('/customers/download/all', 'CustomerController@printAll');
Route::get('/product/download/all', 'ProductController@printAll');
Route::get('/event/download/all', 'EventController@printAll');
Route::get('/order/download/all', 'OrderController@printAll');
Route::get('/coupon/download/all', 'CouponController@printAll');
Route::get('/booking/download/all', 'BookingCoachController@printAll');
Route::get('/contact/download/all', 'ContactRequestController@printAll');
Route::get('/coach/download/all', 'CoachController@printAll');


Route::resource('coaches', 'CoachController');
Route::post('find/coach', 'CoachController@searchCoach')->name('searchCoach');
Route::post('find/product', 'ProductController@searchProduct')->name('searchProduct');
Route::post('find/partner', 'PartnerController@searchPartner')->name('searchPartner');
Route::post('find/event', 'EventController@searchEvent')->name('searchEvent');
Route::post('find/order', 'OrderController@searchOrder')->name('searchOrder');
Route::post('find/bookingCoach', 'BookingCoachController@searchBookingCoach')->name('searchBookingCoach');
Route::resource('product-reservation', 'ProductReservationController');

Route::resource('customers', 'CustomerController');
Route::post('find/customer', 'CustomerController@searchCustomer')->name('searchCustomer');

Route::resource('languages', 'LanguageController');

Route::resource('availabilities', 'AvailabilityController');

Route::resource('disciplines', 'DisciplineController');

Route::resource('coachDisciplines', 'CoachDisciplineController');

Route::resource('packs', 'PackController');

Route::resource('packSubscriptions', 'PackSubscriptionController');

Route::resource('portfolios', 'PortfolioController');

Route::resource('events', 'EventController');

Route::resource('orders', 'OrderController');
Route::post('/order/espece/{id}', 'OrderController@espece')->name('orders.espece');
Route::post('/order/isPaid/{id}', 'OrderController@changeStatus')->name('orders.isPaid');
Route::post('/order/changeStatus/{id}', 'OrderController@changeStatus')->name('orders.changeStatus');
Route::post('/customer/changeStatus/{id}', 'CustomerController@changeStatus')->name('customer.changeStatus');
Route::post('/coach/changeStatus/{id}', 'CoachController@changeStatus')->name('coach.changeStatus');

Route::resource('bodyMassIndices', 'BodyMassIndexController');

Route::resource('recapBMIs', 'RecapBMIController');

Route::resource('recapBMIs', 'RecapBMIController');

Route::resource('addresses', 'AddressController');

Route::resource('coupons', 'CouponController');

Route::resource('invoices', 'InvoiceController');

Route::resource('courses', 'CourseController');
Route::post('/course/changeStatus/{id}', 'CourseController@changeStatus')->name('course.changeStatus');
Route::get('/sendMail', 'HomeController@sendMail')->name('sendMail');
Route::post('/sendMail', 'HomeController@sendMailPost')->name('sendMailPost');
Route::get('viewinvoice/{id}', 'OrderController@invoiceFacture');

Route::resource('services', 'ServiceController');

Route::resource('products', 'ProductController');
Route::post('/product/stock/{id}', 'ProductController@stock')->name('stock_update');

Route::resource('experiences', 'ExperienceController');

Route::resource('qualifications', 'QualificationController');

Route::resource('qualificationTypes', 'QualificationTypeController');

Route::resource('invoicePayments', 'InvoicePaymentController');

Route::resource('invoicePayments', 'InvoicePaymentController');

Route::resource('notes', 'NoteController');

Route::resource('advice', 'AdviceController');

Route::resource('objectives', 'ObjectiveController');

Route::resource('seances', 'SeanceController');


Route::resource('howDidYouKnows', 'HowDidYouKnowController');

Route::resource('partners', 'PartnerController');


Route::resource('connexions', 'ConnexionController');


Route::resource('categories', 'CategoryController');

Route::resource('posts', 'PostController');

Route::resource('orderItems', 'OrderItemController');


Route::resource('courseDetails', 'courseDetailsController');

Route::resource('courseLieus', 'courseLieuController');

Route::resource('lieuCourses', 'LieuCourseController');

Route::resource('courseObjectives', 'CourseObjectiveController');

Route::resource('bookingCoaches', 'BookingCoachController');


Route::resource('productCategories', 'ProductCategoryController');

Route::resource('adverts', 'AdvertController');
Route::resource('users', 'UserController');


Route::get('/mail/test', function () {

    $user = [
        'name' => 'Mahedi Hasan',
        'info' => 'Laravel Developer'
    ];

    \Mail::to('jacques.bagui@gmail.com')->send(new \App\Mail\NewMail($user));

    dd("success");
});

Route::get('videotheque', 'CustomerFrontOfficeController@videothequeIndex');

Route::resource('distinctions', 'distinctionController');

Route::resource('videotheques', 'VideothequeController');





Route::resource('clientTestimonies', 'ClientTestimonyController');

Route::resource('programs', 'ProgramController');


Route::resource('slides', 'SlideController');
Route::resource('diplomes', 'DiplomeController');

Route::resource('customerDevices', 'CustomerDeviceController');

Route::resource('customerNotifications', 'CustomerNotificationController');
Route::post('resend-email', 'CustomerNotificationController@resendEmailSubcription')->name('resendEmailSubcription');





Route::resource('reviews', 'ReviewController');

Route::get('/fetchVisitorsAndPageViews', 'AnalytiqueController@fetchVisitorsAndPageViews');
Route::get('/fetchTotalVisitorsAndPageViews', 'AnalytiqueController@fetchTotalVisitorsAndPageViews');
Route::get('/fetchMostVisitedPages', 'AnalytiqueController@fetchMostVisitedPages');
Route::get('/fetchTimeOnPages', 'AnalytiqueController@fetchTimeOnPages');
Route::get('/fetchTopReferrers', 'AnalytiqueController@fetchTopReferrers');
Route::get('/fetchUserTypes', 'AnalytiqueController@fetchUserTypes');

app/Models/CourseDetail.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class courseDetails
 * @package App\Models
 * @version October 5, 2020, 8:32 pm UTC
 *
 * @property integer $course_id
 * @property string $experience
 * @property string $seance_type
 * @property boolean $is_diplome
 * @property boolean $is_formation
 */
class CourseDetail extends Model
{
    use SoftDeletes;

    public $table = 'course_details';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'course_id',
        'experience',
        'seance_type',
        'is_diplome',
        'diplome_id',
        'diplome_name',
        'diplome_url',
        'nb_person',
        'is_formation',
        'has_particulier',
        'has_collectif'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'course_id' => 'integer',
        'experience' => 'string',
        'seance_type' => 'string',
        'is_diplome' => 'boolean',
        'is_formation' => 'boolean',
        'has_particulier' => 'boolean',
        'has_collectif' => 'boolean'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'course_id' => 'required'
    ];


}

app/Http/Controllers/courseDetailsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreatecourseDetailsRequest;
use App\Http\Requests\UpdatecourseDetailsRequest;
use App\Repositories\courseDetailsRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class courseDetailsController extends AppBaseController
{
    /** @var  courseDetailsRepository */
    private $courseDetailsRepository;

    public function __construct(courseDetailsRepository $courseDetailsRepo)
    {
        $this->courseDetailsRepository = $courseDetailsRepo;
    }

    /**
     * Display a listing of the courseDetails.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $courseDetails = $this->courseDetailsRepository->all();

        return view('course_details.index')
            ->with('courseDetails', $courseDetails);
    }

    /**
     * Show the form for creating a new courseDetails.
     *
     * @return Response
     */
    public function create()
    {
        return view('course_details.create');
    }

    /**
     * Store a newly created courseDetails in storage.
     *
     * @param CreatecourseDetailsRequest $request
     *
     * @return Response
     */
    public function store(CreatecourseDetailsRequest $request)
    {
        $input = $request->all();

        $courseDetails = $this->courseDetailsRepository->create($input);

        Flash::success('Course Details saved successfully.');

        return redirect(route('courseDetails.index'));
    }

    /**
     * Display the specified courseDetails.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $courseDetails = $this->courseDetailsRepository->find($id);

        if (empty($courseDetails)) {
            Flash::error('Course Details not found');

            return redirect(route('courseDetails.index'));
        }

        return view('course_details.show')->with('courseDetails', $courseDetails);
    }

    /**
     * Show the form for editing the specified courseDetails.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $courseDetails = $this->courseDetailsRepository->find($id);

        if (empty($courseDetails)) {
            Flash::error('Course Details not found');

            return redirect(route('courseDetails.index'));
        }

        return view('course_details.edit')->with('courseDetails', $courseDetails);
    }

    /**
     * Update the specified courseDetails in storage.
     *
     * @param int $id
     * @param UpdatecourseDetailsRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatecourseDetailsRequest $request)
    {
        $courseDetails = $this->courseDetailsRepository->find($id);

        if (empty($courseDetails)) {
            Flash::error('Course Details not found');

            return redirect(route('courseDetails.index'));
        }

        $courseDetails = $this->courseDetailsRepository->update($request->all(), $id);

        Flash::success('Course Details updated successfully.');

        return redirect(route('courseDetails.index'));
    }

    /**
     * Remove the specified courseDetails from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $courseDetails = $this->courseDetailsRepository->find($id);

        if (empty($courseDetails)) {
            Flash::error('Course Details not found');

            return redirect(route('courseDetails.index'));
        }

        $this->courseDetailsRepository->delete($id);

        Flash::success('Course Details deleted successfully.');

        return redirect(route('courseDetails.index'));
    }
}

resources/views/course_details/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('courseDetails.index') !!}">Course Details</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Course Details</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'courseDetails.store']) !!}

                                   @include('course_details.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/course_details/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('courseDetails.index') !!}">Course Details</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Course Details</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($courseDetails, ['route' => ['courseDetails.update', $courseDetails->id], 'method' => 'patch']) !!}

                              @include('course_details.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/course_details/fields.blade.php
<!-- Course Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('course_id', 'Course Id:') !!}
    {!! Form::text('course_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Experience Field -->
<div class="form-group col-sm-6">
    {!! Form::label('experience', 'Experience:') !!}
    {!! Form::text('experience', null, ['class' => 'form-control']) !!}
</div>

<!-- Seance Type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('seance_type', 'Seance Type:') !!}
    {!! Form::text('seance_type', null, ['class' => 'form-control']) !!}
</div>

<!-- Is Diplome Field -->
<div class="form-group col-sm-6">
    {!! Form::label('is_diplome', 'Is Diplome:') !!}
    {!! Form::text('is_diplome', null, ['class' => 'form-control']) !!}
</div>

<!-- Is Formation Field -->
<div class="form-group col-sm-6">
    {!! Form::label('is_formation', 'Is Formation:') !!}
    {!! Form::text('is_formation', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('courseDetails.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/course_details/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Course Details</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             courseDetails
                             <a class="pull-right" href="{{ route('courseDetails.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('course_details.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/course_details/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('courseDetails.index') }}">Course Details</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('courseDetails.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('course_details.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/course_details/show_fields.blade.php
<!-- Course Id Field -->
<div class="form-group">
    {!! Form::label('course_id', 'Course Id:') !!}
    <p>{{ $courseDetails->course_id }}</p>
</div>

<!-- Experience Field -->
<div class="form-group">
    {!! Form::label('experience', 'Experience:') !!}
    <p>{{ $courseDetails->experience }}</p>
</div>

<!-- Seance Type Field -->
<div class="form-group">
    {!! Form::label('seance_type', 'Seance Type:') !!}
    <p>{{ $courseDetails->seance_type }}</p>
</div>

<!-- Is Diplome Field -->
<div class="form-group">
    {!! Form::label('is_diplome', 'Is Diplome:') !!}
    <p>{{ $courseDetails->is_diplome }}</p>
</div>

<!-- Is Formation Field -->
<div class="form-group">
    {!! Form::label('is_formation', 'Is Formation:') !!}
    <p>{{ $courseDetails->is_formation }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $courseDetails->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $courseDetails->updated_at }}</p>
</div>

resources/views/course_details/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="courseDetails-table">
        <thead>
            <tr>
                <th>Course Id</th>
        <th>Experience</th>
        <th>Seance Type</th>
        <th>Is Diplome</th>
        <th>Is Formation</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($courseDetails as $courseDetails)
            <tr>
                <td>{{ $courseDetails->course_id }}</td>
            <td>{{ $courseDetails->experience }}</td>
            <td>{{ $courseDetails->seance_type }}</td>
            <td>{{ $courseDetails->is_diplome }}</td>
            <td>{{ $courseDetails->is_formation }}</td>
                <td>
                    {!! Form::open(['route' => ['courseDetails.destroy', $courseDetails->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('courseDetails.show', [$courseDetails->id]) }}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{{ route('courseDetails.edit', [$courseDetails->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>